version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cyfrif_campaign
      MYSQL_USER: campaign_user
      MYSQL_PASSWORD: campaign_password
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3315:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
