version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cyfrif_campaign
      MYSQL_USER: campaign_user
      MYSQL_PASSWORD: campaign_password
    ports:
      - "3378:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8078:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
